import type { OrderItem } from './order-items';
export type Order = {
  reference: string;
  product_name: string;
  size: string;
  color: string;
  quantity: number;
  unit_price: number;
  shipping: number;
  items: OrderItem[];
  shipping_adjustments: {
    id: number;
    old_shipping: number;
    new_shipping: number;
    reason: string;
    created_at: string;
  }[];
  total: number;
  customer_name: string;
  email: string;
  phone: string;
  address: string;
  city: string;
  postal_code: string;
  notes: string;
  payment_method: 'gcash' | 'bank' | 'cod' | 'qr';
  payment_details: string;
  status: string;
  email_status: string;
  created_at: string;
};
