CREATE TABLE IF NOT EXISTS product_images (
 id CHAR(36) PRIMARY KEY,
 data MEDIUMBLOB NOT NULL,
 width INT UNSIGNED NOT NULL,
 height INT UNSIGNED NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
