CREATE TABLE IF NOT EXISTS payment_settings (
 id TINYINT UNSIGNED PRIMARY KEY,
 gcash_enabled BOOLEAN NOT NULL DEFAULT FALSE,
 gcash_details TEXT NOT NULL,
 bank_enabled BOOLEAN NOT NULL DEFAULT FALSE,
 bank_details TEXT NOT NULL,
 cod_enabled BOOLEAN NOT NULL DEFAULT TRUE,
 qr_enabled BOOLEAN NOT NULL DEFAULT FALSE,
 qr_details TEXT NULL,
 qr_image_url VARCHAR(2000) NOT NULL DEFAULT '',
 revision INT UNSIGNED NOT NULL DEFAULT 1,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
