CREATE TABLE IF NOT EXISTS products (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 slug VARCHAR(100) NOT NULL UNIQUE,
 name VARCHAR(100) NOT NULL,
 caption TEXT NOT NULL,
 price INT UNSIGNED NOT NULL,
 color VARCHAR(50) NOT NULL,
 image_url VARCHAR(2000) NOT NULL DEFAULT '',
 sizes JSON NOT NULL,
 active BOOLEAN NOT NULL DEFAULT TRUE,
 design VARCHAR(30) NOT NULL DEFAULT 'off duty',
 ink CHAR(7) NOT NULL DEFAULT '#702c3c',
 bg CHAR(7) NOT NULL DEFAULT '#e9e5dd',
 subtitle VARCHAR(100) NOT NULL DEFAULT '',
 tag VARCHAR(100) NOT NULL DEFAULT '',
 deleted_at TIMESTAMP NULL DEFAULT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
