CREATE TABLE IF NOT EXISTS orders (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 reference VARCHAR(20) NOT NULL UNIQUE,
 idempotency_key CHAR(36) NOT NULL UNIQUE,
 product_slug VARCHAR(100) NOT NULL,
 product_name VARCHAR(100) NOT NULL,
 size VARCHAR(5) NOT NULL,
 color VARCHAR(50) NOT NULL,
 quantity INT UNSIGNED NOT NULL,
 unit_price INT UNSIGNED NOT NULL,
 shipping INT UNSIGNED NOT NULL,
 total INT UNSIGNED NOT NULL,
 items JSON NULL,
 customer_name VARCHAR(100) NOT NULL,
 email VARCHAR(200) NOT NULL,
 phone VARCHAR(25) NOT NULL,
 address VARCHAR(500) NOT NULL,
 city VARCHAR(100) NOT NULL,
 postal_code VARCHAR(10) NOT NULL,
 notes TEXT NOT NULL,
 payment_method ENUM('gcash','bank','cod') NOT NULL DEFAULT 'cod',
 payment_details TEXT NOT NULL,
 status ENUM('pending','paid','processing','shipped','cancelled') NOT NULL DEFAULT 'pending',
 email_status ENUM('pending','sent','failed') NOT NULL DEFAULT 'pending',
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX idx_orders_created (created_at),
 INDEX idx_orders_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
