CREATE TABLE IF NOT EXISTS shipping_settings (
 id TINYINT UNSIGNED PRIMARY KEY,
 metro_manila INT UNSIGNED NOT NULL DEFAULT 12000,
 luzon INT UNSIGNED NOT NULL DEFAULT 12000,
 visayas INT UNSIGNED NOT NULL DEFAULT 12000,
 mindanao INT UNSIGNED NOT NULL DEFAULT 12000,
 free_shipping_threshold INT UNSIGNED NULL,
 revision INT UNSIGNED NOT NULL DEFAULT 1,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
